In [2]:
import pandas as pd

csv_df=pd.read_csv('cars,csv')

csv_df.head()

ModuleNotFoundError: No module named 'pandas'

In [1]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]],dtype=np.float32)
print(a.ndim, a.shape, a.dtype)

2 (2, 3) float32


In [3]:
#array exercise
#1
b = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
b.ndim

3

In [7]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [6]:
a = a.reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
a=a.reshape(2,-1)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a=a.ravel()
a

array([1, 2, 3, 4, 5, 6])

In [14]:
# Transposition
a=np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [15]:
a=a.T
a

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [17]:
a=a.transpose(1,0)
a

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [21]:
np.sqrt(a)

array([[0.        , 1.41421356, 2.        , 2.44948974, 2.82842712],
       [1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ]])